ticket,root cause,root cause type,suggestion,new case automation,component,sub-component,areas,susqa label,detailed analysis,title,new tests required,environment,version,Duplicate,Migration
SPL-117146,Infrastructure/hardware problem,Configuration flaws ,n/a,,Auth,Login,UI,Not labeled,"the root cause of the issue are changes to $SPLUNK_HOME/lib/python2.7/site-packages/httplib2/__init__.py – class ProxyInfo now reads ""https_proxy"" from the environment, causing all python scripts relying on httplib2 to use the configured proxy for their connections. In Parvesh's repro, what we're seeing is that tinyproxy is refusing to talk to localhost, so every python script trying to talk to local splunkd simply fails.","After upgrade to 6.4 from 6.3.3, all users unable to login, receive 500 Internal Server Error",n/a,Standalone,6.4.0 GA (Galaxy),,
SPL-117137,Misconfiguration,Configuration flaws,n/a,,Splunkweb,Appserver,UI,Not labeled,The change happened because we are now building python against a version of OpenSSL that does not export that symbol. Here is the relevant code in Python-2.7.11/Modules/_ssl.c:,When using appServerPorts = 0 and SSL Splunkweb will not start in 6.4.0,n/a,Standalone,6.4.0 GA (Galaxy),,
SPL-117139,Infrastructure/hardware problem,Configuration flaws ,n/a,,Auth,Login,UI,Not labeled,"the root cause of the issue are changes to $SPLUNK_HOME/lib/python2.7/site-packages/httplib2/__init__.py – class ProxyInfo now reads ""https_proxy"" from the environment, causing all python scripts relying on httplib2 to use the configured proxy for their connections. In Parvesh's repro, what we're seeing is that tinyproxy is refusing to talk to localhost, so every python script trying to talk to local splunkd simply fails.",HTTPS_PROXY in splunk-launch.conf causes 500 Internal Server Error after login,n/a,Standalone,6.4.0 GA (Galaxy),TRUE,
